### ISSUE TITLE
ES6 modules incompatibility

### ISSUE THREAD

**Issue by arantir** [thlorenz/browserify-shim#106]
ES6 modules by default import a `default` object from exports.

E.g.
```javascript
import foo from 'bar'
```
actually means (commonjs example):
```javascript
var foo = require("bar")["default"]
```

But browserify-shim sets the whole exports to an exposed object. So the above syntax does not work.

This is standard behaviour, and is used, for example, by [6to5](https://github.com/6to5/6to5) and [traceur](https://github.com/google/traceur-compiler), regardlesgs of whatever modules style they're using. (Traceur use `System.register` and you'll get `'default' is not exported by 'bar'` compilation error. With CommonJS `require()` you just get `foo` as undefined object at runtime.)

So you have to do something like
```javascript
import * as $ from 'jquery'
import * as _ from 'lodash'
import * as angular from 'angular'
```
which is quite illogicall.

Would be nice to have an ability to expose some modules with `default` object or at least to set such behaviour globally (useful if your project is entirely in ES6).

**Comment by bendrucker** [comment]
Closing this since interop is now the default in Babel. If anyone wants to make a docs PR somewhere to clarify things go for it.
