### ISSUE TITLE
Issue when using Highcharts

### ISSUE THREAD

**Issue by kimmobrunfeldt** [thlorenz/browserify-shim#113]
I'm still having the same issue as this https://github.com/thlorenz/browserify-shim/issues/89. I can't get highcharts working with browserify-shim. Browserify doesn't throw any error in build time, but I get this error when opening the page:

    bundle.js:611 Uncaught TypeError: Cannot set property 'exports' of undefined

My package.json looks like this:

```javascript
"browser": {
  "Highcharts": "./bower_components/highcharts/highcharts.src.js",
  "HighchartsAdapter": "./bower_components/highcharts/adapters/standalone-framework.src.js"
},
"browserify": {
  "transform": [
    "browserify-shim"
  ]
},
"browserify-shim": {
  "Highcharts": {
    "depends": [
      "HighchartsAdapter:HighchartsAdapter"
    ],
    "exports": "Highcharts"
  },
  "HighchartsAdapter": {
    "exports": "HighchartsAdapter"
  }
}
```

I separated the issue to smallest possible repository: https://github.com/kimmobrunfeldt/browserify-shim-highcharts-example. **Note:** The index.html page in the repository is empty but you should see console.

**Comment by nkoterba** [comment]
@kimmobrunfeldt Did you ever find a workaround to this?  I'm seeing this same issue with another 3rd party library, Kendo UI.

I get the exact `Uncaught TypeError: Cannot set property 'exports' of undefined.`

I originally was having issues with angular, but once I resolved those (#134) I was then seeing browserify-shim 'double-wrap' my library with shims.  See [my example](https://github.com/thlorenz/browserify-shim/issues/134#issuecomment-75417895).

I ran your example and you too are getting double-wrapped shims:
```javascript
;__browserify_shim_require__=require;(function browserifyShim(module, exports, require, define, browserify_shim__define__module__export__) {
;__browserify_shim_require__=require;(function browserifyShim(module, exports, require, define, browserify_shim__define__module__export__) {
/**
 * @license Highcharts JS v4.0.4 (2014-09-02)
 *
 * Standalone Highcharts Framework
 *
 * License: MIT License
 */
... 
HIGHCHARTS SRC HERE
...

; browserify_shim__define__module__export__(typeof HighchartsAdapter != "undefined" ? HighchartsAdapter : window.HighchartsAdapter);

}).call(global, undefined, undefined, undefined, undefined, function defineExport(ex) { module.exports = ex; });

; browserify_shim__define__module__export__(typeof HighchartsAdapter != "undefined" ? HighchartsAdapter : window.HighchartsAdapter);

}).call(global, undefined, undefined, undefined, undefined, function defineExport(ex) { module.exports = ex; });

}).call(this,typeof global !== "undefined" ? global : typeof self !== "undefined" ? self : typeof window !== "undefined" ? window : {})
```

I actually know how to fix your problem...you do not need to apply the browserify-shim transform from both your npm command **AND** have the transform configured to run in the package.json.  By doing that I think it's "shimming" your modules twice.

E.g. update your build command to this in your package.json.  Then try your build and run command. I was able to get the app to load without any exceptions.  Whether you can actually use highcharts at that point is another question.

```javascript
      "build": "browserify main.js -o bundle.js"
```

Sadly, this doesn't solve my issue.  For whatever reason, I **have** to explicitly run the transform command to get AngularJS to work.  When I do that, though, it double-wraps my Kendo UI library.  I'm not sure why...*sigh*

**Comment by bendrucker** [comment]
In your package `transform` can take an array `[transform, options]`. Use that to enable global shimming. Please keep these issues focused.

**Comment by bendrucker** [comment]
So actually you can't do `options.global` from your package. That's documented as a specifically ignored option in browserify.

**Comment by ankurp** [comment]
@bendrucker I am also running into same issue. I have the shim defined as such
```
  "browser": {
    "highcharts": "vendor/highcharts/highcharts-2.0.1.js",
    "jquery": "vendor/jquery/jquery-1.11.0.js"
  },
  "browserify-shim": {
    jquery": {
      "exports": "$"
    },
    "highcharts": {
      "depends": [
        "jquery"
      ],
      "exports": "Highcharts"
    }
  },
  "browserify": {
    "transform": [
      "browserify-shim"
    ]
  }
```
and using it as such `var highcharts = require("highcharts");` and it always returns an empty object. How do I return the global Highcharts object in highcharts script.

**Comment by bendrucker** [comment]
Please make sure your paths are strictly relative (start with `./`). This is also not the same issue, though you're shimming the same package. Please open a new issue with a minimal reproduction I can clone and run with a single command to reproduce the issue.
