### ISSUE TITLE
Shim export line not being added to certain files

### ISSUE THREAD

**Issue by gabrielecirulli** [thlorenz/browserify-shim#116]
I have a browserify setup where I can shim bower modules (also using [shimbro](https://github.com/mattdesl/shimbro)).

I've installed `headroom.js` through bower and added the following fields to `package.json`:

```
{
  "browserify": {
    "transform": [
      "6to5-browserify",
      "browserify-shim"
    ]
  },
  "browserify-shim": {
    "headroom": "Headroom"
  },
  "browser": {
    "headroom": "./bower_components/headroom.js/dist/headroom.js"
  }
}
```

For some reason, no matter what I do, the line 

```
; browserify_shim__define__module__export__(typeof Headroom != "undefined" ? Headroom : window.Headroom);
```

won't be added to the bottom of the file, no matter what.

To be clear, looking in the bundled result the file is present in full (because I required it in my application code), but the module export line is not there.

-----------

Also, at some point while I was trying to fix it, the line was there but requiring the file was returning an empty object. Even placing `console.log` calls in the source file printing `window.Headroom` were showing the expected object, but it wasn't being exported at all.

-------

I can do without Headroom for the time being but this problem is quite unsettling because I couldn't figure out what was happening and more importantly why.

Am I doing something wrong?

**Comment by bendrucker** [comment]
We need a reproducible example to look at this

**Comment by gabrielecirulli** [comment]
Sorry for the lack of response. I ended up removing that library from my code, and haven't had problems with browserify-shim since. I think we can close this.

**Comment by bendrucker** [comment]
No worries. Doesn't sound like a b-shim issue to me. Cheers!
