### ISSUE TITLE
browserify-shim and proxyquireify compatibility

### ISSUE THREAD

**Issue by camwest** [thlorenz/browserify-shim#117]
I'm having a problem getting these two libraries to play nicely together. I have proxyquireify and browserify-shim working independently, but when I try to proxyquire a shimmed global, things don't go so well. I understand that browserify-shim is transforming the require statement into a global assignment:

```javascript
var myLib = require('MyLib');
```

Becomes:

```javascript
var  web = (typeof window !== "undefined" ? window.MyLib : typeof global !== "undefined" ? global.MyLib : null);
```

Since it bypasses require, there is no way for proxyquire to replace it with the stubbed version. I'd like the developers on the project to have a single way to stub modules whether they are shimmed or not. Any advice? Below are some sample files for context:

```javascript
// shims.js
module.export = {
  'MyLib': { exports: 'global:MyLib' }
} 
```

```javascript
//foo.js
var myLib = require('MyLib');

module.exports = function() {
  myLib.doThing();
}
```

```javascript
//fooSpec.js

var proxyquire = require('proxyquireify')(require);

describe('foo', function() {
  var foo, fakeMyLib, thingDone;

  beforeEach(function() {
    thingDone = false;

    fakeMyLib = {
      doThing: function() { thingDone = true; }    
    };

    foo = proxyquire('./foo', { 'MyLib': fakeMyLib });
  });

  it('does the thing', function() {
    foo();
    expect(thingDone).to.equal(true);
  });
});
```

**Comment by bendrucker** [comment]
The order of the transforms is going to determine whether this is possible. If proxyquireify runs before b-shim, I think this will work.
