### ISSUE TITLE
How do you expose multiple variables?

### ISSUE THREAD

**Issue by EvanCarroll** [thlorenz/browserify-shim#122]
Prototype.js pollutes the window object with multiple varaibles.. (Class, Ajax, etc).. How do I tell browserify-shim to make all this pollution available to other things being shimmed? Or, how do I say that the things being shimmed require access to this stuff?

**Comment by bendrucker** [comment]
There's no way to do that. You'd need to write a custom shim yourself to handle that sort of behavior.

**Comment by EvanCarroll** [comment]
Can you explain then so I can better understand what browserify-shim can and can't do? It would seem like this would be the ideal case? Why does it work with Three.js and not Prototype.js?

**Comment by EvanCarroll** [comment]
I went ahead and opened a question on StackExchange about this.. http://stackoverflow.com/questions/27769690/how-do-i-shim-prototype-js-to-work-in-browserify

**Comment by thlorenz** [comment]
There is only **one** thing that b-shim assigns to the module exports.
This isn't saying that it wouldn't be possible for another tool to support multiple exports. However this is a very special use case and we choose to not support it since otherwise the API for the most common case (one export) would become more complex then we like.

**Comment by thlorenz** [comment]
However in your special case `prototype` you should just be able to `require('prototype')` since it doesn't export anything because it actually changes JS prototypes.

Not recommending these kind of libraries, but that's besides the point.

**Comment by EvanCarroll** [comment]
Well, why would it be more complex? What about a patch that simply supports an array value for exports? `"exports": "String"`, or `"exports": ["String", "String2"]` etc.

**Comment by EvanCarroll** [comment]
I also can't get `require('prototype')` to work? Doesn't prototype.js export things [`Class`](http://api.prototypejs.org/language/Class/create/), [`Ajax`](http://api.prototypejs.org/ajax/Ajax/), and [`$`](http://api.prototypejs.org/dom/dollar/)?

**Comment by thlorenz** [comment]
Go ahead and try to add the feature without changing existing API.
At that point we can discuss pulling it in.

And yes prototype exports things I guess, wasn't aware since I never used it.

**Comment by EvanCarroll** [comment]
I'm still having problems -- though I think I've hacked in a working patch. I just can't get prototype to work at all with this shim..

```js
, "browser": {                          
    "ppprototype": "lib/prototype-1.7.js" 
}
, "browserify-shim": {                 
    "ppprototype": { "exports": "Class" }
}
```

And, I still get ` Uncaught ReferenceError: Class is not defined sampBase.js:14`

```text
 11                                                                |  initialize: function() {                                        
 12 require('ppprototype');                                        |    this.panelList = [];         // array that holds a list of the
 13                                                                | currently installed panels                                       
 14 var Samp = Class.create( {
```

**Comment by EvanCarroll** [comment]
https://github.com/thlorenz/browserify-shim/pull/123
