### ISSUE TITLE
Any ideas on why this browserify-shim for jquery.jgrowl doesn't work?

### ISSUE THREAD

**Issue by ScottWeinstein** [thlorenz/browserify-shim#124]
Here's the setup:

      "browserify": {
        "transform": [ "browserify-shim" ]
      },
      "browser": {
        "jquery": "./vendor/jquery-1.11.0",
        "jquery.jgrowl": "./vendor/jquery.jgrowl-1.2.13"
      },
      "browserify-shim": {
        "jquery": "jQuery",
        "jquery.jgrowl": { "depends": "jquery" }
      }

The generated bundle doesn't include jquery. 

[Demo project](https://github.com/ScottWeinstein/browserify-shim-jquery-jgrowl-issue)

**Comment by thlorenz** [comment]
Are you `require`ing `jquery` or `jquery.jgrowl` anywhere?

**Comment by thlorenz** [comment]
From the demo looks like you are, but your `depends` config is not complete.
Should be more like `depends: jquery:$`.

**Comment by ScottWeinstein** [comment]
Thanks for the suggestion.

my index.js is just `var jg = require('jquery.jgrowl');`

I tried this change, but it didn't have an impact.

        "jquery": "$",
        "jquery.jgrowl": { "depends": "jquery:$" }

Here's the output of the diagnostics messages:

>   [ 'Found "jquery" in browser field referencing "./vendor/jquery-1.11.0" and resolved it to "PATH\\vendor\\jquery-1.11.0"',
>     'Found "jquery.jgrowl" in browser field referencing "./vendor/jquery.jgrowl-1.2.13" and 
>     resolved it to "PATH\\vendor\\jquery.jgrowl-1.2.13"',
>     'Found depends "jquery" exposed in browser field',
>     { resolved:
>        { 'PATH\\vendor\\jquery-1.11.0': { exports: '$', depends: undefined },
>          'PATH\\vendor\\jquery.jgrowl-1.2.13': { exports: null, depends: { jquery: '$' } } } } ] }

also, if I do modify the index.js to also `var $ = require('jquery');` then the src of jquery is included in the bundle, but it's not a real fix. When run in a browser, it gives **jQuery is not defined** at the jgrowl IIFE.

**Comment by bendrucker** [comment]
Items under `browser` need to be proper paths as they need to be resolved with `path.resolve` and not `require.resolve`. You should notice at the end that you were getting an `ENOENT`. Once the paths are fixed everything works as expected:

https://github.com/bendrucker/browserify-shim-jquery-jgrowl-issue/compare/ScottWeinstein:master...master

**Comment by ScottWeinstein** [comment]
Thanks! So simple, I just couldn't see it.

Odd though that jgrowl was pulled in. Also, on my machines (windows) I didn't see any errors `ENOENT` or otherwise.

**Comment by thlorenz** [comment]
Maybe file an issue w/ browserify to let them know that errors are being swallowed on windows. You could use your repro in it's original form to show the problem.
Although few committers there are running windows and won't be able to repro and probably they'll just tell you to use a real operating system :-P
