### ISSUE TITLE
Dependency can't require a global

### ISSUE THREAD

**Issue by paulmelnikow** [thlorenz/browserify-shim#125]
Hi there, I'm exposing a global in my app's package.json:

```json
  "browserify-shim": {
    "three": "global:THREE"
  },
```

I load Three.js in a script tag, and `require('three')` works fine.

My app also has some code in a private, browserify-aware dependency, which also requires Three.js. I used the same `browserify-shim` options in its package.json. But when I try to `require('three')` in the dependency, and require the dependency from the app, I get this error when I run browserify:

```
>> Error: Cannot find module 'three' from '/Users/pnm/code/my-app/node_modules/my-dependency/src'
```

Seems to work okay if I use `window.THREE` in the dependency.

Any idea what might be causing this? I'm happy to go digging but need some advice on where to start.

**Comment by paulmelnikow** [comment]
Wondered if this was related to #46 but it seems not. This error happens when browserify runs.

**Comment by thlorenz** [comment]
You need to specify the same config in your dependency as well since transforms apply locally, therefore browserifys-shim only applies to your main package as is now and doesn't transform the dep.

**Comment by yinso** [comment]
Running into this issue as well. 

What does it mean to "specify the same config in dependency"? Is it something like the following?

    "browser-shim": {
      "three": "global:THREE",
      "foo": {
        "depends": [
          {"three": "global:THREE"} // what goes here? this doesn't work.
        ]
      }
    }

**Comment by thlorenz** [comment]
@yinso no, you'd have to define it in the `package.json` of the dependency.
Alternatively you could PR on the dependency if it tries `require` `three` without providing it since that is a bug.

**Comment by mtraynham** [comment]
@thlorenz I'm getting the same issue with my app, yet have no sub-dependency.  I try to expose angular as global.
```
    "browserify": {
        "transform": [
            "browserify-shim"
        ]
    },
    "browserify-shim": {
        "angular": "global:angular"
    }
```

Yet receive the following error: 
```>> TS2307: app/Module.ts(3,26): TS2307: Cannot find external module 'angular'.```

I'm using `tsify` as a plugin, but that should seem unrelated.  This happened with the upgrade to 3.8.2, which was caused by `tsify`'s dependency on browserify 8.  Also using `grunt-browserify`, but this worked befored I added `tsify`.

**Comment by paulmelnikow** [comment]
Thanks for the info. I've tried a simpler example and it seems to work find. Opened #126 in case you'd like to include it in the repository for others.

Not sure why it's not working in my actual project. Maybe an issue with grunt-browserify. Going to keep digging.

**Comment by paulmelnikow** [comment]
Working now, using this config in the dependency's package.json.

```json
  "browserify-shim": {
    "three": "global:THREE"
  },
  "browserify": {
    "transform": [
      "browserify-shim"
    ]
  }
```
