### ISSUE TITLE
Browserify Shim and Bower

### ISSUE THREAD

**Issue by EvanCarroll** [thlorenz/browserify-shim#127]
There is still code in the test case for Bower.. 

> https://github.com/thlorenz/browserify-shim/blob/923661abd6ab32ce7e8f81c7734f9916dcb0745d/test/bower/package.json

It says, 

>     "@fixPackages": "./components",

That said, I can't find @fixPackages documented anywhere. Any advice on how to get bower to work. I even tried to delete the package.json that bower installed. It simply can't find the module. Browserify works, but when I `require` it in the shimmed module as a dependency, I get the path with `../../` prepended.

**Comment by bendrucker** [comment]
Fix packages was proposed in a long discussion of how to handle Bower (https://github.com/thlorenz/browserify-shim/issues/30#issuecomment-35926075) and ultimately did not need to be implemented. 

As for the particular issue you're seeing, please set up a repo we can `git clone`, `npm install`, and `npm test` to reproduce whatever you're seeing.

**Comment by EvanCarroll** [comment]
Try this.. don't forget `bower install` in that list above.

**Comment by bendrucker** [comment]
There's way too much going on there. You're using debowerify and passing custom require paths to browserify. Then there's all the extraneous stuff, including gulp and watchify. To clarify what I mean by reproducible:

* `npm install`: please just check the bower components into source so I don't have to wonder whether they're matching your setup
* `npm test`: I want to be able to run `npm test` and get a 0 or 1 exit code depending on whether things worked. It's time consuming to guess about whether you're seeing browserify errors in Node or only once the bundle is built and opened. Please just write a script that calls `assert` either from Node or in the browser such that I can pop it open and check the console.

If you can get a proper repo online I'm happy to help you get your config right but this does not seem to be a b-shim issue.
