### ISSUE TITLE
requiring jQuery plugin without exposing jQuery to global scope

### ISSUE THREAD

**Issue by omarfouad** [thlorenz/browserify-shim#139]
Hi, 
I've been using the jQuery `npm` module till yesterday when I decided to use the `jquery.payment` plugin (also an `npm` package). Not surprisingly the plugin needs jQuery to be loaded on `window` so the following code didn't work:

```js
var $ = require('jquery');
require('jquery.payment');
```
The only way I could get this to work, is to expose jQuery globally, so on package.json

```json
"browser": {
    "jquery":"./vendor/jquery.js"
},
"browserify-shim": {
    "jquery": "$"
}
```
And that's an issue because for production, I don't want to expose a library like jQuery on the console. 

Any ideas?

**Comment by bendrucker** [comment]
Please do a sample repo so I can see if there's a way to do this.

**Comment by thlorenz** [comment]
Looks like you need to properly declare what depends on what as [outlined here](https://github.com/thlorenz/browserify-shim#multi-shim-example-including-dependencies).
You shouldn't need to `require` jquery in your code.
That being said I'd think about putting jquery into my bundle (way too big), instead use the [expose globals feature](https://github.com/thlorenz/browserify-shim#a-expose-global-variables-via-global)

**Comment by bendrucker** [comment]
I assumed that had been done. The problem with stuff on npm that's not a proper module is that transforms will ignore them by default. So even if you set up dependencies as Thorsten mentioned you're still not going to get the correct results. 

See #107

**Comment by omarfouad** [comment]
I see. I had to convert the jquery plugin into a non jquery dependent code to make it work.
