### ISSUE TITLE
Multiple shims to match browserifys multiple bundles

### ISSUE THREAD

**Issue by lukemcgregor** [thlorenz/browserify-shim#140]
Browserify has the concept of multiple bundles, you can create separate bundles which act independently.

It would be great if you could independently manage the shims for each bundle. Currently you can only define one list of shims and have the option of applying all or none to a specific bundle. It would be great if you could apply separate lists of shims to each bundle.

**Comment by bendrucker** [comment]
This amounts to the same request as #65. We'll take a PR for allowing options to be passed directly but it could be a while until Thorsten or I get around to it.

**Comment by wizardzloy** [comment]
Hey Guys, is this functionality added? If not I'd +1 for it.

**Comment by bendrucker** [comment]
No, but I understand why people want it (no +1 needed). Per #65, we'd like to review a PR and otherwise it's not likely in the short term.

**Comment by bendrucker** [comment]
If you have anything to add please do so in #65
