### ISSUE TITLE
How to expose jquery & to make it work with jquery-ui - question

### ISSUE THREAD

**Issue by dragonflypl** [thlorenz/browserify-shim#142]
Hi,
i'm learning browserify-shim. So I started with with simple example that simulates that jquery is taken from CDN:

<pre><code> // package.json
    "browserify-shim": {
        "jquery": "global:$"
    },
    "browserify": {
        "transform": [
            "browserify-shim"
        ]
    },

// entry.js
var $ = require('jquery');
console.log($().jquery);

// build.js
var browserify = require('browserify'),
    fs = require('fs');

browserify()
    .require('./entry.js', { entry: true })
    .bundle()
    .on('end', function() { console.log('OK');})
    .on('error', console.error.bind(console))
    .pipe(fs.createWriteStream('browserified-entry.js', 'utf8'));

</code></pre>

When I execute `node build.js`, `browserified-entry.js` looks as expected. I has:

```
﻿var $ = (typeof window !== "undefined" ? window.$ : typeof global !== "undefined" ? global.$ : null);
console.log($().jquery);
```
Now I've installed jquery-ui with `npm install jquery-ui`. I've changed `entry.js` to the following:

<pre><code>var $ = require('jquery');
require('jquery-ui');
console.log($().jquery);
// doing sth with jquery-ui here....</code></pre>

And now when I execute `node build.js` I get this error:

<blockquote>Error: Cannot find module 'jquery' from 'D:\dev\learning-browserify\node_modules\jquery-ui'</blockquote>

Could you please help me what I'm doing wrong?

**Comment by bendrucker** [comment]
Seems that `jquery-ui` tries to call `require('jquery')`. You'll need to shim `jquery-ui` in order to tell it to expect jquery as `window.jQuery` instead. There's a minor trick to shimming modules installed with npm because browserify transforms will usually skip them. Basically you have to manually map to the main file in your `browser` fields in your `package.json`. More on that in #107.

**Comment by bs-thomas** [comment]
For the latest JQuery UI 1.12.1, this is what I did and seemed to work for me:

var $ = require('jquery');
$.ui = require('jquery-ui/ui/widget.js');

Not sure if it's the right way to do it.  If not, please do point out, as I'm using this on production and I definitely want to be on the safe side.

**Comment by Borvik** [comment]
I realize this may be old, but I stumbled upon this while trying to find a solution - and came up with another solution.  Doesn't use browserify-shim.

```
'use strict';
let $ = require('jquery');
global.jQuery = global.$ = $;

require('jquery-ui');
```
