### ISSUE TITLE
Issues with babelify

### ISSUE THREAD

**Issue by reggi** [thlorenz/browserify-shim#145]
Put this in the same boat with: #49

I wanted to dive a little deeper.

```
"transform": [ "babelify", "browserify-shim"]
```
When my config has `babelify` first I get the following error. Here's the code for this [bundle](https://gist.github.com/reggi/e96a1ace0a6acc019d5c#file-babelify-first-js).

```
Uncaught TypeError: Cannot set property 'esprima' of undefined
```

---

```
"transform": [ "browserify-shim", "babelify"]
```

When the shim is first, I get the following error, Here's the code for that [bundle](https://gist.github.com/reggi/e96a1ace0a6acc019d5c#file-shim-first-js).

```
__browserify_shim_require__ is not defined
```

---

```
"transform": [ "browserify-shim"]
```

When I don't include babelify everything works. Here's the [bundle without babelify](https://gist.github.com/reggi/e96a1ace0a6acc019d5c#file-without-babelify-js)

My `index.js` file is super simple

```
var Polymer = require("polymer")
console.log(Polymer)
```

and the shim in package.json looks like this

```
  "browserify": {
    "transform": [
      "browserify-shim"
    ]
  },
  "browser": {
    "polymer": "./bower_components/polymer/polymer.js"
  },
  "browserify-shim": {
    "polymer": "Polymer"
  }
```

**Comment by bendrucker** [comment]
Please put this in a repo we can clone and run to reproduce this. I use babel + b-shim without any issues so the info above doesn't offer any info.

**Comment by reggi** [comment]
@bendrucker Here it is: https://github.com/reggi/demo-browserify-polymer-es6

**Comment by bendrucker** [comment]
Thanks for the thoroughness. Not sure precisely why this is happening, but the easy fix is to have Babel ignore Polymer and anything else installed with bower entirely (https://github.com/babel/babelify#additional-options). That would also provide a nice speed bump as well.

**Comment by reggi** [comment]
If I use `[browserify-shim babelify --only \"index.js\"]` and I have `import Polymer from "polymer"` I get "Unexpected reserved word" @ "import", leading me to belive I need babelify before `browserify-shim`. The same configuration with `var Polymer = require("polymer")` it works.

I feel like it should be something like this `[babelify --only \"index.js\" browserify-shim babelify --only \"index.js\"]` this would switch the `index.js` to es6 browserify would convert the import and the shim can include it then babelify runs again and picks up the uses everything. Howerver that's giving me an error with Polymer `"Observer is not define"`.

@bendrucker  Thoughts?

**Comment by bendrucker** [comment]
Babelify has to run first otherwise browserify-shim can't parse the code. Upstream the require detection is done by [detective](https://github.com/substack/node-detective). You only need to transform with babelify once.

**Comment by reggi** [comment]
@bendrucker Thanks for your help, makes sense for babilfy to run first. I opened an issue with babelify. Very confused as to why I can't get this working still.

**Comment by bendrucker** [comment]
It's entirely possible that it's a b-shim issue and that they're going to say they have no clue what's going on.
