### ISSUE TITLE
browserify-shim silently errors

### ISSUE THREAD

**Issue by gpleiss** [thlorenz/browserify-shim#147]
Hello!

Right now, if browserify-shim doesn't find certain files, there's no error reported. e.g. if I had the following code:

```json
  "browserify-shim": {
    "jsdkfja-module-that-does-not-exist": "someVar"
  }
```

everything will run without error.

**Comment by bendrucker** [comment]
If you don't require that string there's nothing for browserify-shim to replace. It wouldn't make sense to throw when a shim isn't found, nor is it possible.

**Comment by gpleiss** [comment]
What about a warning?

**Comment by bendrucker** [comment]
I'm typically of the "throw or do nothing" mentality. But that aside, this isn't even possible. Transforms run on each file. By definition most of your shims aren't used from b-shim's perspective.
