### ISSUE TITLE
shim doesn't work when aliased modules uses a shortened path name

### ISSUE THREAD

**Issue by gpleiss** [thlorenz/browserify-shim#148]
I had the following code in my package.json:

```json
  "browser": {
    "maki": "maki/dist/maki",
    "maki-ga-classic-adapter": "maki-ga-classic-adapter/maki.ga-classic"
  },
  "browserify-shim": {
    "maki-ga-classic-adapter": {
      "depends": [
        "maki:maki"
      ]
    },
  }
```

Both `maki` and `maki-ga-classic-adapter` are node modules. The shim didn't work though.

When I changed the "browser" field to the following:

```json
  "browser": {
    "maki": "./node_modules/maki/dist/maki.js",
    "maki-ga-classic-adapter": "./node_modules/maki-ga-classic-adapter/maki.ga-classic.js"
  }
```

it worked. Both the `./node_modules/` and the `.js` are required. It would be nice to use the shortened path name.

**Comment by bendrucker** [comment]
This is because Browserify transforms normally ignore packages in `node_modules` but using a `browser` alias treats the `require` like a regular relative path instead.

**Comment by gpleiss** [comment]
Is there any chance this could be documented somewhere? I wrestled with this for 4 hours before I figured it out :)

**Comment by bendrucker** [comment]
Yes! I actually reverted something that documented it: 2a71c78611a8937556a90308160c22c2c7a9ad9f

This was coming up most often with Angular and I just landed proper CJS support there soon after we initially committed docs with Angular as the example.

**Comment by bendrucker** [comment]
PR welcome, otherwise I'll get to this as soon as I can to save people the frustration in the future
