### ISSUE TITLE
Cannot find module 'browserify-shim' when developing in child directory?

### ISSUE THREAD

**Issue by kopepasah** [thlorenz/browserify-shim#153]
When running `browserify`, I get the following warning:

```Warning: Cannot find module 'browserify-shim' from '/path-to-project/project'```.

I am wondering if this is because I am developing in a sub directory (e.g. `project/develop`) and, if not, do you have any suggestions of how to fix this issue.

The project in question is [here](https://github.com/juko-labs/han/tree/master/develop). For this project I am using `grunt` to handle running `browserify`.

Any help is appreciated.

**Comment by bendrucker** [comment]
If you can reproduce this without Grunt we can help. Otherwise there's too much going on here to figure out whether browserify-shim is even involved.
