### ISSUE TITLE
Shimmed modules can't use libraries being pulled in from a CDN as dependencies

### ISSUE THREAD

**Issue by chadwatson** [thlorenz/browserify-shim#156]
I'm getting jQuery from the Google CDN.

```html
<script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
```

Then using a shim file, and linking to it in my `package.json`.
*package.json*
```json
"browserify": {
	"transform": [
		"browserify-shim",
		"browserify-ejs"
	]
},
"browserify-shim": "./_src/js/config/shim.js"
```
*shim.js*
```javascript
module.exports = {
	'jquery': { 'exports': 'global:$' },
	'../lib/jquery.throttleDebounce.js': { 'depends': { 'jquery' : null } }
}
```

Using my custom Gulp script I receive the following error:
```bash
[13:37:04] gulp-notify: [Compile Error] Error: Cannot find module 'jquery' from '/Users/chadwatson/Projects/gulp-starter/_src/js/lib'
```

I can successfully use `require('jquery')` in all of my modules.

I can't seem to find any documentation on how to shim global modules from an external script and then use them as a dependency for a shimmed module in browserify-shim.

**Comment by bendrucker** [comment]
We need code here — please post the contests of jquery.throttleDebounce.js

**Comment by LoicMahieu** [comment]
I think your problem is that browserify-shim does not transform whole sources, only local to your project. By default, browserify does not "transform" every modules required. For enable global transforming, use `global` option. I found solution into issue: https://github.com/thlorenz/browserify-shim/issues/143

**Comment by bendrucker** [comment]
Ah yes, didn't catch the external script mention. If this isn't the case please say so and I can reopen.

**Comment by chadwatson** [comment]
Thanks for the replies!
