### ISSUE TITLE
Tests fail on io.js

### ISSUE THREAD

**Issue by bendrucker** [thlorenz/browserify-shim#163]
There are some reference errors around window not being defined. This is just a reminder for me to come back and look at it.

**Comment by thlorenz** [comment]
Thanks Ben, I also noticed these but didn't have time to look into them.
From what I can tell they are related to jsdom.
I tried to upgrade jsdom but that made things worse. At that point I ran out of time.

Here's what I'd suggest:

- upgrade to latest jsdom, fix the calls to it so tests pass on 0.10
- hope that they also pass in 0.12 and io.js
- if not we have a bigger problem
