### ISSUE TITLE
shim jquery

### ISSUE THREAD

**Issue by aschwersenz** [thlorenz/browserify-shim#165]
In the docs it says here https://github.com/thlorenz/browserify-shim#3-provide-browserify-shim-config that "The above includes ./js/vendor/jquery.js (relative to the package.json) in the bundle and exports window.$.", so in my understanding the following should work:

_ I have a jquery-2.1.4.min.js in a folder ./assets/vendor/
_ I'm adding this code to my package.json

```json
  "browserify": {
    "transform": [ "browserify-shim" ]
  },
  "browserify-shim": {
    "./assets/vendor/jquery-2.1.4.min.js": "$"
  }
```

_ I have a js file with `console.log(window.$)`

But when I'm running browserify with this configuration jquery gets not included in my bundle and the console.log() returns undefined.

Why? Am i missing something?

**Comment by bendrucker** [comment]
Can you post the JS where jQuery is required?

**Comment by aschwersenz** [comment]
Never mind, I completely misunderstood what browserify shim is doing. Got it now :)
