### ISSUE TITLE
Example project browserify, gulp, emebr ?

### ISSUE THREAD

**Issue by b-long** [thlorenz/browserify-shim#170]
I'm trying to understand how browserify and ember can be used together in a gulp build, but having some difficulty.  Could someone provide an example that expands on this? https://github.com/thlorenz/browserify-shim/wiki/browserify-shim-recipes#ember-which-depends-on-handlebars-and-jquery

Thanks!

**Comment by bendrucker** [comment]
Please elaborate on what you're having trouble with as that example looks fine to me
