### ISSUE TITLE
Use browserify-shim in a build script (i.e. with Browserify's JS API)?

### ISSUE THREAD

**Issue by cperryk** [thlorenz/browserify-shim#173]
Is there a way to use browserify-shim with [Browserify's JS API](https://github.com/substack/node-browserify#api-example)? Like:

```
var browserify = require('browserify');
var b = browserify();
b.transform('browserify-shim', {'jquery':'$'})
b.bundle(writeBundle)
// ...etc.
```
When I run something like this, I get the error message: `Unable to find a browserify-shim config section in the package.json` It doesn't make much sense to me to put the config in package.json unless you are using browserify via the command line.

**Comment by bendrucker** [comment]
There is not right now. See #146 among others.
