### ISSUE TITLE
fetch failed http://registry.cnpmjs.org/esprima-fb/download/esprima-fb-3001.1.0-dev-harmony-fb.tgz

### ISSUE THREAD

**Issue by pansheng10000** [thlorenz/browserify-shim#174]
HI
I want to install browserify-shim. But it's error.
This is error code.

npm ERR! fetch failed http://registry.cnpmjs.org/esprima-fb/download/esprima-fb-3001.1.0-dev-harmony-fb.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 404

How can i do?

**Comment by bendrucker** [comment]
Not sure what's up with your private npm but unfortunately it isn't a proxyquire bug so we can't do much here

**Comment by AisonBird** [comment]
Same problem. I have change the version, but still not work.

**Comment by bendrucker** [comment]
Please don't ping old issues without info. This isn't a browserify-shim bug.
