### ISSUE TITLE
no longer checking global in 3.8.8

### ISSUE THREAD

**Issue by lukemcgregor** [thlorenz/browserify-shim#175]
Behaviour in 3.8.7

    require('underscore') => (typeof window !== "undefined" ? window._ : typeof global !== "undefined" ? global._ : null);

Behaviour in 3.8.8

    require('underscore') => (window._);

This is a pretty major breaking change that makes browserify shim not work with server side code.

**Comment by bendrucker** [comment]
Somehow https://github.com/thlorenz/exposify/commit/0765d033cf5514107b45a192fead7a9a54a76e0d managed to sneak into a release but isn't in master. We recently bumped exposify here and so it disappeared. Will take care of this in a bit and we can cut an exposify patch.

**Comment by lukemcgregor** [comment]
Awesome :)
