### ISSUE TITLE
Since the last update, my global browserify shims are broken

### ISSUE THREAD

**Issue by STuFF** [thlorenz/browserify-shim#176]
Hi, maybe I'm doing it wrong, but my global shim are declared like that :
```  
"browserify-shim": {
    "Vendors/jQuery": "global:$"
  }
```

and used in my code like that :
```
var $ = require('Vendors/jQuery');
```

I've supposed the shim will override any browserify behavior, so the module name I used (Vendors/jQuery) will never be considered as a path. Until yesterday it was working fine, now the build failed :
```
Running "browserify:prod" (browserify) task
>> Error: ENOTDIR, stat '/usr/local/bin/node/Vendors/jQuery'
```
Everything is ok if I change to "jQuery": "global:$" (no / in the module name)

I don't know if it's a very nasty regression or if I misused the function.

**Comment by miralize** [comment]
:thumbsup: getting this too

**Comment by bendrucker** [comment]
Can you please pin your version so we know exactly where this broke?

**Comment by STuFF** [comment]
it works until 3.8.7
3.8.8 and 3.8.9 are broken for me.

**Comment by bendrucker** [comment]
Can you create a repro project I can clone and run?

**Comment by STuFF** [comment]
ok

**Comment by STuFF** [comment]
here it is https://github.com/STuFF/browserify-shim-test

**Comment by bendrucker** [comment]
Believe this should be fixed upstream if you do a fresh install
