### ISSUE TITLE
injecting a global

### ISSUE THREAD

**Issue by vvo** [thlorenz/browserify-shim#177]
Hi, I was wondering if given this file:

file.js
```
(function($) {
  // use $
})(window.jQuery)
```

I was able to inject `window.jQuery = require('jquery');` by using browserify-shim?

I cannot make it work, the only thing I want is to `require('./vendor/file.js')` with window.jQuery being a commonJS reference to jQuery (since we can now `require('jquery')`

Thanks!

**Comment by bendrucker** [comment]
What config are you using?

**Comment by vvo** [comment]
@bendrucker I was more asking on a feature side if that was feasible.

**Comment by bendrucker** [comment]
Well it should work

**Comment by vvo** [comment]
So what would be the configuration to use to inject `window.jQuery` as `require('jquery')` in a file tree containing a package.json and a file2.js being required in index.js with `require('./file2.js')` that look like:

```js
(function($) {
  // use $
})(window.jQuery)
```

?

**Comment by bendrucker** [comment]
If I'm understanding right, this should be in the pkg:

```json
{
  "browserify-shim": {
    "./file2.js": {
      "depends": "jquery:jQuery"
    }
  }
}
```

**Comment by vvo** [comment]
Thanks, what would be the configuration if `./file.2` is `moduleName`?

Like

app.js
```js
var module = require('moduleName');
```

moduleName
```
(function($) {
  // use $
})(window.jQuery)
```

Vasically I am trying to force to use my node_modules jQuery to typeahead (0.10.5): https://github.com/twitter/typeahead.js/blob/v0.10.5/dist/typeahead.bundle.js

thx @bendrucker

**Comment by bendrucker** [comment]
So that story gets a bit more complicated. Browserify transforms don't run on code in `node_modules` unless you make it a global transform. 

```sh
browserify -e app.js -g browserify-shim
```

```json
{
  "module-name": {
    "depends": "jquery:jQuery"
  }
}
```

**Comment by bendrucker** [comment]
Assuming this is resolved, please update if it isn't

**Comment by vvo** [comment]
Thanks for the answer, did not know about global transforms. Sorry for late reply
