### ISSUE TITLE
v3.8.9 cannot handle paths

### ISSUE THREAD

**Issue by daprahamian** [thlorenz/browserify-shim#180]
Before 3.8.9, it used to be possible to include a path to a global variable to expose. Example:

```js
"browserify-shim": {
    "Marionette": "window:Backbone.Marionette"
}
```

It looks like [this change in exposify](https://github.com/thlorenz/exposify/commit/9cac1cf38602f8b6c6dc15db8191e8fb3b91f465#diff-30b7f327e2feed5e47e8fbff41e51049) now makes the window lookup look like `window["Backbone.Marionette"]`, which is not the same as `window.Backbone.Marionette`. Is it possible to fix this to obtain the previous functionality? Thanks!

**Comment by bendrucker** [comment]
Hmm. That's via https://github.com/bendrucker/globo/pull/2. globo could special-case periods and require that they be escaped if you want it to be a string prop via brackets rather than a dot prop.

**Comment by bendrucker** [comment]
Do me a favor and file there and I'll take care of this today.
