### ISSUE TITLE
Having a hard time shimming FontFaceObserver

### ISSUE THREAD

**Issue by silvenon** [thlorenz/browserify-shim#186]
I thought [fontfaceobserver](https://github.com/bramstein/fontfaceobserver) is an easy target, because it exports `window.FontFaceObserver`, so I tried the following:

```json
"browserify-shim": {
  "fontfaceobserver": "FontFaceObserver"
}
```

Unfortunately it didn't work :( When I tried to instantiate `FontFaceObserver`, this was the error:

```
Uncaught TypeError: _fontfaceobserver2.default is not a function
```

Do you want a test case?

Btw, I :heart: browserify-shim, great work!

**Comment by bendrucker** [comment]
Test case would be helpful, but I'm not sure how much we can do here. The project ships with a pretty gross minified built file as the main.

**Comment by silvenon** [comment]
I thought it doesn't matter since it's clear what it exports. Yeah, it's minified with Closure Compiler, but it's not that unreadable when you [beautify it](https://gist.github.com/silvenon/e5ece747e996df20c2f6).

I'm just really curious what's happening. I guess I should dig into what exactly browser-shim is doing.

**Comment by bendrucker** [comment]
Yeah if you investigate we'd be happy to take a PR if needed. This isn't something I can spend time on myself at the moment.

**Comment by bendrucker** [comment]
If you have more info and it's clear b-shim could be doing something differently we can reopen this one
