### ISSUE TITLE
npm WARN EPEERINVALID browserify-shim@3.8.10 requires a peer of browserify@>= 2.3.0 < 12 but none was installed.

### ISSUE THREAD

**Issue by gitawego** [thlorenz/browserify-shim#189]
with npm 3.3.4, I can't install browserify-shim any more.  it gaves error:

```
npm WARN EPEERINVALID browserify-shim@3.8.10 requires a peer of browserify@>= 2.3.0 < 12 but none was installed.
```

I think in npm 3, peerDependencies aren't auto-installed any more.

**Comment by bendrucker** [comment]
Why do have b-shim without browserify alongside it?

**Comment by gitawego** [comment]
hmm... I'm using keystone which configured like this which causes such error. I just created an issue in keystone repo.  I think maybe it should be kept as this for module browserify-shim
