### ISSUE TITLE
Browserify-shim globally for all dependencies

### ISSUE THREAD

**Issue by laxity7** [thlorenz/browserify-shim#191]
In my project I use gulp + browserify + browserify-shim. In the project I connect other libraries which are in the node_modules folder. There is such problem that I and one of libraries use the same dependence - bluebird. But I connect `bluebird` globally, and I don't want to pack. In package.json I have such a rule
```
"browserify": {
    "transform": ["browserify-shim"]
},
"browserify-shim": {
    "bluebird": "global:Promise",
}
```
But this rule doesn't extend on others to library and therefore bluebird is all the same packed.

Itself task looks standardly

```
gulp.task ('testjs', function () {
    var b = browserify ({
        entries: 'app.js'
    });

    return b
        .transform (babelify, { "global": "true", "compact": "false" })
        .bundle ()
        .pipe (source ('app.js'))
        .pipe (gulp.dest ('./dist'));
});
```

How to force to distribute this rule globally to any connected libraries and their dependences?

In an ideal it would be desirable to see settings as at babelify, you put `"global":"true"` and everything works, but didn't find such for Browserify-shim

**Comment by bendrucker** [comment]
You can do the same and specify the transform with the `options.global` flag. Just exclude it from your package.json.

**Comment by laxity7** [comment]
you could show on the example of my code as to make it?

**Comment by bendrucker** [comment]
`b.transform('browserify-shim', {global: true})`

**Comment by laxity7** [comment]
It's clear=)
how to configure browserify-shim, if to delete from package.json?

**Comment by bendrucker** [comment]
Yes, you cannot define global transforms in your package. They must be done programmatically w/ the browserify API.

**Comment by xueruini** [comment]
@thlorenz 

two questions:
1. Will the browserify API merge options in program and `package.json`?
2. If there were other transforms in `package.json`, such `babelify`, should all of them be present w/ the api style in program?

**Comment by bendrucker** [comment]
1. No
2. If you want to apply a transform globally, it cannot be included in package.json

**Comment by xueruini** [comment]
> 1. No

If option is not provided in the program, will the API read options in `package.json`?

> 2. If you want to apply a transform globally, it cannot be included in package.json

For the given `package.json`:
```json
"browserify": {
  "transform": ["x", "y", "z"]
}
```

I found no matter how many `transform()` were added, the generated bundle is the same with the demo code:

   ```js
browserify()
  // enabling any number of the three `transform()` lead to the same result.
  // .transform('x')
  // .transform('y')
  // .transform('z')
  .bundle(myOutputStream)
   ```

Does it mean `browserify()` will load transforms in `package.json` not presented in the code?

**Comment by bendrucker** [comment]
Options support will come with #195. Browserify will run all transforms every time they're specified, whether via the package or via the API. Some transforms may be able to run multiple times without causing issues, others may not.

**Comment by kottenator** [comment]
@bendrucker:

> Yes, you cannot define global transforms in your package. They must be done programmatically w/ the browserify API.

But why not?
