### ISSUE TITLE
Can I remove shimmed dependencies from the global scope?

### ISSUE THREAD

**Issue by arcticShadow** [thlorenz/browserify-shim#194]
I have the following config in my package.json:
```JSON
"browser": {
    "uikit": "./node_modules/uikit/dist/js/uikit.js",
    "uikit.css": "./node_modules/uikit/dist/css/uikit.css",
    "uikit/autocomplete": "./node_modules/uikit/dist/js/components/autocomplete.js",
    "uikit/autocomplete.css": "./node_modules/uikit/dist/css/components/autocomplete.css",
    "uikit/pagination": "./node_modules/uikit/dist/js/components/pagination.js"
  },
  "browserify": {
    "transform": [
      "browserify-shim",
      "browserify-css"
    ]
  },
  "browserify-shim": {
    "uikit": {
      "exports": "UIkit",
      "depends": [
        "jquery:window.jQuery",
        "uikit.css"
      ]
    },
    "uikit/autocomplete": {
      "depends": [
        "uikit:window.UIkit"
      ]
    }
```

As you may be able to tell, I am trying to get uikit to play nicely with CommonJS style loading.

The above works. in my Javascript files, i can 
```javascript
import uikit from 'uikit';
import uikitautocomplete from 'uikitautocomplete'
```
And both `uikit` and `uikitautocomplete` are available on the `uikit` object. (This is the way uikit works)

However, I have noticed that `UIkit` and `jQuery` objects are available globally whenever I `import` uikit. Can i stop this from happenning?

**Comment by bendrucker** [comment]
Short answer is no, verdict is here: https://github.com/thlorenz/browserify-shim/issues/137#issuecomment-84628544

**Comment by arcticShadow** [comment]
Ahh bother. Thanks for that link - missed it when i looked earlier.
