### ISSUE TITLE
Multiple package.json in one app

### ISSUE THREAD

**Issue by xueruini** [thlorenz/browserify-shim#200]
I come to a weird shim error with the following dirs. `package.json` exists in both the top-level folder (a) and sub-folder (b).

```shell
~ $  tree a
a
├── a.js
├── b
│   ├── b.js
│   └── package.json
└── package.json
```

Both `package.json` files have different b-shim configurations, and `b.js` is required by `a.js` like 

```js
# a.js
require('./b/b.js');
```

When executing `browserify -t browserify-shim a.js`, I found `b/package.json` was taking effect. I think `a.js` is the entry file, so `a/package.json` should be read, and during requiring, `b/package.json` will not be read any more. But it seems not.

**Comment by bendrucker** [comment]
The nearest parent package.json with b-shim config will always be read. This is expected behavior.
