### ISSUE TITLE
browserify-shim fails to process require('') in ParsleyJS

### ISSUE THREAD

**Issue by mfursov** [thlorenz/browserify-shim#202]
Here is a first line from ParsleyJS (v2.2.0-rc4)

```javascript
  typeof exports === 'object' && typeof module !== 'undefined' ? module.exports = factory(require('jquery')) : typeof define === 'function' && define.amd ? define(['jquery'], factory) : global.parsley = factory(global.jQuery);
```

The "require('jquery')" is not processed by shim module, and as the result 'jquery' sources are always included into the final bundle by browserify.

**Comment by bendrucker** [comment]
Can you provide your shim config please?

**Comment by mfursov** [comment]
Here is snippet from my package.json:

```
"browserify-shim": {
    "jquery": "global:$"
  },
  "browserify": {
    "transform": [
      "browserify-shim"
    ]
  }
```

**Comment by mfursov** [comment]
I tried to add deps & export section like it shown here but it also does not work: jquery is included anyway. Tried both 'parsley' & 'parsleyjs' module names.

http://w3javascript.com/question/make-parsley-js-work-with-require-js/

**Comment by mfursov** [comment]
Adding         
```
.transform('browserify-shim', {global: true})
```
to by gulpfile.js solves the problem: no more jquery is embedded. Looks like I missed some documentation how to set this flag in package.json without use of gulp.

Complete gulp pipeline:
```javascript

gulp.task('build', function () {
    return browserify('./src/site.js')
        .transform(partialify)
        .transform('browserify-shim', {global: true})
        .bundle()
        .pipe(source('site.js'))
        .pipe(gulp.dest('./package/js/'));
});
```

**Comment by bendrucker** [comment]
> how to set this flag in package.json

You can't. Running transforms on your npm dependencies based on a package flag is not something browserify supports/will support. Think of it this way: package flags are things that are essential to run *your* package itself, e.g. using babelify to convert ES6 to ES5. 

If you want to do transforms like uglifying or shimming to your dependencies, you can *only* use the API.
