### ISSUE TITLE
Browserify 13.0.0 has been released, and browserify-shim needs to update it's dependencies to support it

### ISSUE THREAD

**Issue by jaapz** [thlorenz/browserify-shim#204]
Currently browserify-shim wants browserify >=2.3.0 < 13, so I can't install the newest version of browserify.

**Comment by bendrucker** [comment]
https://github.com/thlorenz/browserify-shim/issues/203

**Comment by jaapz** [comment]
Ah sorry, for some reason I completely missed that issue. Thanks!
