### ISSUE TITLE
Material-ui support

### ISSUE THREAD

**Issue by gradosevic** [thlorenz/browserify-shim#213]
Hi contributors,

I was wondering if there is a way to use material-ui with browserify-shim? I have an existing project based on browserify shims, and official [Material UI docs](https://github.com/callemall/material-ui) require imports of multiple components from the specific locations like this:

`import MuiThemeProvider from 'material-ui/styles/MuiThemeProvider';`

I have no idea how to add this to package.json. Any suggestions? 

Thanks,
Goran

**Comment by bendrucker** [comment]
What are you asking for help with? Happy to try to point you in the right direction but would appreciate a specific question based on your attempt to implement this yourself.
