### ISSUE TITLE
Shim modules that use undeclared variables in the global scope

### ISSUE THREAD

**Issue by mikehaertl** [thlorenz/browserify-shim#220]
I try to transform [a "module"](https://github.com/yiisoft/yii2/blob/ee92cfa7ba618bf4acc19ab540eaa674b828a092/framework/assets/yii.js) that defines a variable in the global scope without `var`:

```
yii = (function ($) {
    var pub = {
    }
    return pub;
})(jQuery);
```

Unfortunately this does not work. When I import this into my project I end up with a `Uncaught ReferenceError: yii is not defined` in the browser, obviously because this code is not strict, and you can not mix strict + non-strict code in a single file. 

So I wonder is this supposed to work? And if not, can this be implemented in browserify-shim or am i completely out of luck here?

Here's the relevant part from my `package.json`:

```
 "devDependencies": {
    ...
    "browserify-shim": "^3.8.12",
  },
  "browserify": {
    "transform": [
      "browserify-shim",
      ["babelify", {
        "presets": "es2015"
      }]
    ]
  },
  "browserify-shim": {
    "../../vendor/yiisoft/yii2/assets/yii.js": "yii"
  },
  "scripts": {
    "js:browserify": "browserify -d scripts/main.js > main.js && touch main.js.map",
  }
```

**Comment by bendrucker** [comment]
Hi, sorry this didn't get a response. At the moment browserify shim doesn't get around the strict mode violation you've described.
