### ISSUE TITLE
Peer browserify-shim@3.8.12 wants browserify@>= 2.3.0 < 14

### ISSUE THREAD

**Issue by feross** [thlorenz/browserify-shim#224]
I just released browserify v14. You might want to bump your peer dependency range.

Also, is there any reason you don't just allow all versions >= 2.3.0, since most of the time that will work just fine?

**Comment by thlorenz** [comment]
> Also, is there any reason you don't just allow all versions >= 2.3.0, since most of the time that will work just fine?

That'd be an option at this point.
In the past I didn't wanna do that as things were still in flux too much, but I feel like things have stabilized.
@bendrucker what do you think?

**Comment by bendrucker** [comment]
Sound good to me. I'm always resistant to allowing an unbounded range of major versions but I think it's safe to say the transform API will never change at this point.
