### ISSUE TITLE
Calling two functions in the same javascript file

### ISSUE THREAD

**Issue by juanpabloaj** [thlorenz/browserify-shim#228]
If I have this javascript file 

```
// hello.js
var hello = function () {
  return 'hello';
};

var bye = function () {
  return 'bye bye';
};
```

I can use `hello()` with this configuration

```
"browserify": {
    "transform": ["browserify-shim"]
  },
  "browser": {
    "hello": "./hello.js"
  },
  "browserify-shim": {
    "hello": {"exports": "hello"}
  }
```

And call with 

```
var hello = require('hello');
hello()
```

How can I use the both functions  `bye()` and `hello()` ?

**Comment by bendrucker** [comment]
browserify-shim is only capable of handling one export per module so at the moment it cannot accomplish what you're requesting.
