### ISSUE TITLE
Support passing options directly to transform function

### ISSUE THREAD

**Issue by gabegorelick** [thlorenz/browserify-shim#42]
Currently, the only config that can be passed to browserify-shim is via package.json (although package.json can point to an external config file). There are certain times when passing options directly to the transform function can be useful, for example, when browserify-shim is run multiple times in the same project but with different settings.

**Comment by enzy** [comment]
And what about a case, when package.json is not available (writable) at all?
We would like to use shim in [mango-cli](https://github.com/manGoweb/mango-cli) (kind of gulp wrapper) where projects don't have it's own package.json file.

**Comment by bendrucker** [comment]
It's a low priority but we'd consider a PR.
