### ISSUE TITLE
Parent and child share dependency

### ISSUE THREAD

**Issue by bendrucker** [thlorenz/browserify-shim#48]
I can't seem to figure out how to write a reusable Angular module and app that both share the same Angular dependency. Both install Angular through bower and then refer to it in the package config:

``` json
{
  "browserify": {
    "transform": [
      "browserify-shim"
    ]
  },
  "browser": {
    "angular": "./app/bower_components/angular/angular.js",
    "angular-mocks": "./app/bower_components/angular-mocks/angular-mocks.js"
  },
  "browserify-shim": {
    "angular": "angular",
    "angular-mocks": {
      "depends": [
        "angular"
      ]
    }
  }
}
```

The module's config is essentially identical. How can I configure the child module so that it uses the Angular module brought in by the parent app?

**Comment by mattfysh** [comment]
hi @thlorenz - angular will be deduped in the output, but I've noticed that when I add the jquery 'depends' entry, the deduping no longer occurs. The require(jquery) is replaced with an absolute path, which is different per package, e.g. parent wraps angular
```
require('/Users/me/project/node_modules/jquery/jquery.min.js')
<angular content>
```
and child wraps angular
```
require('/Users/me/project/node_modules/dep/node_modules/jquery/jquery.min.js')
<angular content>
```
any ideas? am I doing it wrong? thanks!

**Comment by bendrucker** [comment]
Please open a new issue.
