### ISSUE TITLE
Browserify Shim and es6ify incompatibility: __browserify_shim_require__ is not defined

### ISSUE THREAD

**Issue by johnkpaul** [thlorenz/browserify-shim#49]
I'm trying to use browserify shim and es6ify and I keep getting this same error in my bundle. If I remove es6ify, everything works correctly.

I have an example at https://github.com/johnkpaul/es6ify-bshim-incompatability

The error that I'm getting is shown here. 
![screenshot 2014-04-20 13 01 57](https://cloud.githubusercontent.com/assets/475621/2751069/07653390-c8ae-11e3-8657-a3e72b6a775b.png)

I've tried switching the order of es6ify and debugging through the shim, but haven't gotten anywhere. Any help would be appreciated. Thanks.

**Comment by reggi** [comment]
I'm getting this error right now :(
Trying to narrow down why it's happening.

**Comment by bendrucker** [comment]
This issue persists with up to date versions, but browserify-shim + babelify works fine. Just opened a PR that adds `var`. The original example doesn't work because Ember is strict mode incompatible. Everything else can be addressed in es6ify.
