### ISSUE TITLE
Unable to shim Ladda

### ISSUE THREAD

**Issue by ruimarinho** [thlorenz/browserify-shim#85]
`Ladda` is bundling a `package.json` on its bower distribution which breaks `browserify-shim`. Before submitting a PR suggesting the removal of this file, I'd like to understand why the recent modifications on `browserify-shim` that deal with this issue were not enough to ignore it (previously implemented as `@fixPackages`). The reason for shimming `Ladda` is that another component that I am using expects `Ladda` to be exposed on the `window` object. 

A test case is available at [ruimarinho/browserify-ladda](https://github.com/ruimarinho/browserify-ladda), hopefully enabling you to help me identify what I am doing wrong.

**Comment by tonestrike** [comment]
I know this is really old, but would it be possible to post the solution to this? The git repositories no longer exist and I am having the same issue.
