### ISSUE TITLE
TypeError when shimming Angular

### ISSUE THREAD

**Issue by pmdarrow** [thlorenz/browserify-shim#88]
When I require Angular using `var angular = require('angular');`, I get the error `Uncaught TypeError: Cannot set property 'exports' of undefined`. I'm using the following config in my `package.json`:

``` json
  "browserify": {
    "transform": [
      "browserify-shim"
    ]
  },
  "browser": {
    "angular": "./bower_components/angular/angular.min.js"
  },
  "browserify-shim": {
    "angular": {
      "exports": "angular"
    }
  }
```

I've created a repo demonstrating this issue. Clone https://github.com/pmdarrow/browserify-shim-issue.git, run `gulp` and open http://localhost:8080 to see it in action.

**Comment by cdaringe** [comment]
@pmdarrow, thanks!  that was my issue too.  a shim in the `package.json` and in my debug `browserify -t browserify-shim ...` cmd
