### ISSUE TITLE
Inline browserify transforms cause undeclared global reference

### ISSUE THREAD

**Issue by mattidupre** [thlorenz/browserify-shim#93]
Extending on #65, if you call browserify-shim inline with the global flag, i.e., ```b.transform({global: true}, shim);``` or ```b.transform({global: true}, 'browserify-shim');```, 
 you will get a call to an undefined global value in the final output.

The use case for this is referenced in https://github.com/thlorenz/browserify-shim/issues/92#issuecomment-56351962 which suggests a better fix anyway.

Making note of this caveat in the wiki, but just wanted to make sure this issue was indexed should you choose to move forward with inline options.

Issue can be reproduced in https://github.com/mattidupre/browserify-shim-problems/commit/401675206f5d4526153a5f3ccae20fb9a508dfaf by cloning and...
* Executing ```npm install```
* Opening ```index.html``` and noting correct behavior
* Executing ```node test1.js > bundle.js``` and refreshing ```index.html``` *This reflects the default behavior when a module in ```/node_modules``` is shimmed with a dependency also in ```/node_modules```: the dependency is not included in the bundle.*
* Executing ```node test2.js > bundle.js``` and refreshing ```index.html``` *This reflects the default behavior when the global flag is added to b.transform(): ```Uncaught ReferenceError: global is not defined```*
* Appending ```"browserify": { "transform": "browserify-shim" }``` to package.json, executing ```node test3.js > bundle.js```, and refreshing ```index.html``` *This demonstrates expected behavior from test2 by moving the config to package.json.*
*Note that test1 and test2 produce the same result with ```b.transform('browserify-shim');```*

**Comment by bendrucker** [comment]
Fully supporting the exclusive use of transform options is one of those things that would help a small number of people at a pretty high development cost. Not sure if this remains an issue. If transform options comes up in the future we'll revisit this and make sure it gets fixed.
